export type StoredObject = {
  id: string,
  createdAt: string,
  updatedAt: string
}

/**
 * @brief Type of a snapshot
 * The data is stored in json, in the same format as the json generated by the
 * marcelle Dataset.download method
 */
export type DatasetSnapshot = StoredObject & {
  name: string;
  data: string;
}
